apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: booking-platform
type: Opaque
stringData:
  DATABASE_URL: "postgresql://CHANGE_ME:CHANGE_ME@postgres:5432/booking_db"
  RABBITMQ_URL: "amqp://CHANGE_ME:CHANGE_ME@rabbitmq:5672/"
  REDIS_URL: "redis://redis:6379/0"
